import React from 'react';
import { Link } from 'react-router-dom';
import { Map, Zap, Target, Bot } from 'lucide-react';

const Home = () => {
  return (
    <div className="min-h-screen bg-slate-900 text-white font-sans">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16 text-center">
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-8">
          Navigate Your <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">AI Career</span>
        </h1>
        <p className="text-xl md:text-2xl text-slate-400 max-w-3xl mx-auto mb-10">
          Upload your resume, discover your skill gaps, and get a personalized, AI-generated roadmap to land your dream tech job.
        </p>
        <Link to="/register" className="inline-flex items-center justify-center px-8 py-4 text-lg font-bold text-white transition-all duration-200 bg-blue-600 border border-transparent rounded-full hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-600">
          Get Started For Free
        </Link>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <FeatureCard 
            icon={<Target className="w-10 h-10 text-blue-400" />}
            title="ATS Scoring"
            description="Get instant feedback on your resume's ATS compatibility and keywords."
          />
          <FeatureCard 
            icon={<Zap className="w-10 h-10 text-emerald-400" />}
            title="Skill Gap Analysis"
            description="Discover exactly what skills you're missing for your target role."
          />
          <FeatureCard 
            icon={<Map className="w-10 h-10 text-purple-400" />}
            title="AI Roadmaps"
            description="Week-by-week personalized learning plans generated by Gemini AI."
          />
          <FeatureCard 
            icon={<Bot className="w-10 h-10 text-pink-400" />}
            title="AI Chatbot"
            description="24/7 career guidance from our intelligent AI assistant."
          />
        </div>
      </div>
    </div>
  );
};

const FeatureCard = ({ icon, title, description }) => (
  <div className="bg-slate-800 p-8 rounded-2xl border border-slate-700 hover:border-slate-500 transition-colors">
    <div className="mb-4">{icon}</div>
    <h3 className="text-xl font-bold mb-2 text-white">{title}</h3>
    <p className="text-slate-400 leading-relaxed">{description}</p>
  </div>
);

export default Home;
